name: Testando aplicação

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: npm install

    - name: Compilar TypeScript
      run: npm run build 

    - name: Executar testes
      run: npm run start && npm test
