name: Node.js CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x', '20.x']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm ci

      - name: Compilar TypeScript
        run: npm run build --if-present

      - name: Executar testes
        run: npm test
