name: Node.js CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x']

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: verticalLogistica
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm ci

      - name: Compilar TypeScript
        run: npm run build --if-present

      - name: Configurar variáveis de ambiente
        run: |
          export PORT=3000
          export DB_HOST=localhost
          export DB_PORT=5432
          export DB_USERNAME=postgres
          export DB_PASSWORD=password
          export DB_DATABASE=verticalLogistica
          
      - name: Start Server
        run: npm start &
      
      - name: Aguardar servidor iniciar
        run: sleep 5s

      - name: Executar testes
        run: npm test
