name: Node.js CI

on:
  push:
    branches:
      - main 
      
jobs:
  build:
    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x']

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: verticalLogistica
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências
        run: npm ci

      - name: Criar arquivo .env
        run: |
          echo "DB_HOST=localhost" > .env
          echo "PORT=3000" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_DATABASE=verticalLogistica" >> .env 
          echo 'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/verticalLogistica?schema=public"' >> .env

      - name: Compilar TypeScript
        run: npm run build --if-present
          
      - name: Rodar Migrations
        run: npx prisma migrate dev
          
      - name: Start Server
        run: npm start &
      
      - name: Aguardar servidor iniciar
        run: sleep 5s

      - name: Executar testes
        run: npm test
